# Generated by Django 2.2.2 on 2020-06-04 06:06

import blog1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0003_auto_20200603_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=2, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=blog1.models.upload_location, width_field='width_field'),
        ),
    ]
