# Generated by Django 2.2.2 on 2020-06-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0016_auto_20200608_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
    ]
