# Generated by Django 2.2.2 on 2020-06-09 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0019_remove_post_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='draft',
        ),
    ]
