# Generated by Django 2.2.2 on 2020-06-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0013_auto_20200608_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='draft',
            field=models.BooleanField(),
        ),
    ]
