# Generated by Django 2.2.2 on 2020-06-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0018_auto_20200608_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
    ]
