# Generated by Django 2.2.2 on 2020-06-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0025_auto_20200609_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
